//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSApp.Resources.Login.LoginView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMSApp.Resources.Login.LoginView.LoginView", typeof(LoginView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string AppNo {
            get {
                return ResourceManager.GetString("AppNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm quit?.
        /// </summary>
        internal static string AppQuit {
            get {
                return ResourceManager.GetString("AppQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string AppYes {
            get {
                return ResourceManager.GetString("AppYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon.
        /// </summary>
        internal static string BtnLabelLogon {
            get {
                return ResourceManager.GetString("BtnLabelLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password can not be empty, please input Password, and try again..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Server address was not in correct format, please try again later, or contact administrator for help, Thanks.
        /// </summary>
        internal static string invalidServerAddrs {
            get {
                return ResourceManager.GetString("invalidServerAddrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Id can not be empty, please input User Id, and try again..
        /// </summary>
        internal static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string LabelCompany {
            get {
                return ResourceManager.GetString("LabelCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        internal static string LabelSwicthPasswordVisible {
            get {
                return ResourceManager.GetString("LabelSwicthPasswordVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string LabelUserId {
            get {
                return ResourceManager.GetString("LabelUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error received server authentication token.
        /// </summary>
        internal static string langitepty90Header {
            get {
                return ResourceManager.GetString("langitepty90Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server can&apos;t recognised this login, please check the login details, and try again, Thanks [ITEPTY90].
        /// </summary>
        internal static string langitepty90Message {
            get {
                return ResourceManager.GetString("langitepty90Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string langitepty90Ok {
            get {
                return ResourceManager.GetString("langitepty90Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error received server authentication token.
        /// </summary>
        internal static string langitepty93Header {
            get {
                return ResourceManager.GetString("langitepty93Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server can&apos;t recognised this login, please check the login details, and try again, Thanks [ITEPTY93].
        /// </summary>
        internal static string langitepty93Message {
            get {
                return ResourceManager.GetString("langitepty93Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string langitepty93Ok {
            get {
                return ResourceManager.GetString("langitepty93Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We getting mis-matched replied information from the server, Please try again later, or contact administrator for help, Thanks..
        /// </summary>
        internal static string misMatchReplied {
            get {
                return ResourceManager.GetString("misMatchReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server login error, working off line?.
        /// </summary>
        internal static string offLineHeader {
            get {
                return ResourceManager.GetString("offLineHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure the UserId and Password were correct, and try again. Or Tap &apos;Yes&apos; to work offline, for submit transaction when online later..
        /// </summary>
        internal static string offLineMessage {
            get {
                return ResourceManager.GetString("offLineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string offLineMessageNo {
            get {
                return ResourceManager.GetString("offLineMessageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working off line.
        /// </summary>
        internal static string offLineMessageYes {
            get {
                return ResourceManager.GetString("offLineMessageYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place code in between of read line.
        /// </summary>
        internal static string ScannerMiddleText {
            get {
                return ResourceManager.GetString("ScannerMiddleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan result :.
        /// </summary>
        internal static string scanResultHeader {
            get {
                return ResourceManager.GetString("scanResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        internal static string scanTestAccept {
            get {
                return ResourceManager.GetString("scanTestAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string scanTestCancel {
            get {
                return ResourceManager.GetString("scanTestCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press TEST connection, to test. Press RETURN to login screen.
        /// </summary>
        internal static string scanTestConnectMsg {
            get {
                return ResourceManager.GetString("scanTestConnectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string testConnectCancel {
            get {
                return ResourceManager.GetString("testConnectCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string testConnectSave {
            get {
                return ResourceManager.GetString("testConnectSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection test successfully.
        /// </summary>
        internal static string testConnectSuccessHeader {
            get {
                return ResourceManager.GetString("testConnectSuccessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press OK to save or CANCEL to leave this screen..
        /// </summary>
        internal static string testConnectSuccessMsg {
            get {
                return ResourceManager.GetString("testConnectSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string ToolBarItem_ConnectStatus_Connected {
            get {
                return ResourceManager.GetString("ToolBarItem_ConnectStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        internal static string ToolBarItem_ConnectStatus_Reconnect {
            get {
                return ResourceManager.GetString("ToolBarItem_ConnectStatus_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string ToolbarItem_Quit {
            get {
                return ResourceManager.GetString("ToolbarItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Server Address.
        /// </summary>
        internal static string ToolbarItem_SetupLinkWeb_Addr {
            get {
                return ResourceManager.GetString("ToolbarItem_SetupLinkWeb_Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Server Address QR.
        /// </summary>
        internal static string ToolbarItem_SetupLinkWeb_Qr {
            get {
                return ResourceManager.GetString("ToolbarItem_SetupLinkWeb_Qr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection error, please try again later [LCx00].
        /// </summary>
        internal static string translateAlertLCx00 {
            get {
                return ResourceManager.GetString("translateAlertLCx00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later [LCx01].
        /// </summary>
        internal static string translateAlertLCx01 {
            get {
                return ResourceManager.GetString("translateAlertLCx01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later [LCx02].
        /// </summary>
        internal static string translateAlertLCx02 {
            get {
                return ResourceManager.GetString("translateAlertLCx02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user id, please verify and try again. Thanks. [ECx00].
        /// </summary>
        internal static string translateErrECx00 {
            get {
                return ResourceManager.GetString("translateErrECx00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password, please verify and try again . Thanks [ECx01].
        /// </summary>
        internal static string translateErrECx01 {
            get {
                return ResourceManager.GetString("translateErrECx01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ViewScanCancel {
            get {
                return ResourceManager.GetString("ViewScanCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP Login.
        /// </summary>
        internal static string ViewTiltleLogin {
            get {
                return ResourceManager.GetString("ViewTiltleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Server Address in QR Code.
        /// </summary>
        internal static string ViewTitlteScanner {
            get {
                return ResourceManager.GetString("ViewTitlteScanner", resourceCulture);
            }
        }
    }
}
