//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginView_zh_Hans {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginView_zh_Hans() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = 
                        new global::System.Resources.ResourceManager("WMSApp.Resources.LoginView", typeof(LoginView_zh_Hans).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string ToolBarItem_ConnectStatus_Connected {
            get {
                return ResourceManager.GetString("ToolBarItem_ConnectStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        internal static string ToolBarItem_ConnectStatus_Reconnect {
            get {
                return ResourceManager.GetString("ToolBarItem_ConnectStatus_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string ToolbarItem_Quit {
            get {
                return ResourceManager.GetString("ToolbarItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Server Address.
        /// </summary>
        internal static string ToolbarItem_SetupLinkWeb_Addr {
            get {
                return ResourceManager.GetString("ToolbarItem_SetupLinkWeb_Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Server Address QR.
        /// </summary>
        internal static string ToolbarItem_SetupLinkWeb_Qr {
            get {
                return ResourceManager.GetString("ToolbarItem_SetupLinkWeb_Qr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP Login.
        /// </summary>
        internal static string ViewTiltleLogin {
            get {
                return ResourceManager.GetString("ViewTiltleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Server Address in QR Code.
        /// </summary>
        internal static string ViewTitlteScanner {
            get {
                return ResourceManager.GetString("ViewTitlteScanner", resourceCulture);
            }
        }
    }
}
