//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSApp.Resources.Login.ChngWebApiConnView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChngWebApiConnView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChngWebApiConnView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMSApp.Resources.Login.ChngWebApiConnView.ChngWebApiConnView", typeof(ChngWebApiConnView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string addressEmptyTitle {
            get {
                return ResourceManager.GetString("addressEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string addressEmptyTitleConfirm {
            get {
                return ResourceManager.GetString("addressEmptyTitleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address can not be empty. Please contact administrator for help, Thanks..
        /// </summary>
        internal static string addressEmptyTitleMessage {
            get {
                return ResourceManager.GetString("addressEmptyTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string addressIncorrectConfirm {
            get {
                return ResourceManager.GetString("addressIncorrectConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server address supply not in correct format, Please try again later, or contact administrator for help, Thanks..
        /// </summary>
        internal static string addressIncorrectMessage {
            get {
                return ResourceManager.GetString("addressIncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string addressIncorrectTitle {
            get {
                return ResourceManager.GetString("addressIncorrectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string addressMismacthConfirm {
            get {
                return ResourceManager.GetString("addressMismacthConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We getting mis-matched replied information from the server. Please try again later, or contact administrator for help, Thanks..
        /// </summary>
        internal static string addressMismacthMessage {
            get {
                return ResourceManager.GetString("addressMismacthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string addressMismacthTitle {
            get {
                return ResourceManager.GetString("addressMismacthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        internal static string BtnLabelTestConnect {
            get {
                return ResourceManager.GetString("BtnLabelTestConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server address.
        /// </summary>
        internal static string LabelWebApiInstru {
            get {
                return ResourceManager.GetString("LabelWebApiInstru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample server address:.
        /// </summary>
        internal static string LabelWebApiSvrAddrs {
            get {
                return ResourceManager.GetString("LabelWebApiSvrAddrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string successConfirmCancel {
            get {
                return ResourceManager.GetString("successConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string successConfirmSave {
            get {
                return ResourceManager.GetString("successConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press OK to save, or CANCEL to leave this screen..
        /// </summary>
        internal static string successMessage {
            get {
                return ResourceManager.GetString("successMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection test successfully.
        /// </summary>
        internal static string successTitle {
            get {
                return ResourceManager.GetString("successTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup link (Web).
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ToolbarItemCancel {
            get {
                return ResourceManager.GetString("ToolbarItemCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connect and save.
        /// </summary>
        internal static string ToolbarItemTestAndSave {
            get {
                return ResourceManager.GetString("ToolbarItemTestAndSave", resourceCulture);
            }
        }
    }
}
